-- MySQL Script generated by MySQL Workbench
-- Fri Oct  6 10:29:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pvp1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pvp1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pvp1` DEFAULT CHARACTER SET utf8 ;
USE `pvp1` ;


-- -----------------------------------------------------
-- Table `pvp1`.`TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvp1`.`TipoDocumento` (
  `idTipoDocumento` VARCHAR(5) NOT NULL,
  `TipoDocumento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvp1`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvp1`.`Rol` (
  `idRol` VARCHAR(25) NOT NULL,
  `EstadoRol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvp1`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvp1`.`Ciudad` (
  `idCiudad` INT NOT NULL,
  `NombreCiudad` VARCHAR(45) NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvp1`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvp1`.`Usuario` (
  `PKNUsuario` INT NOT NULL,
  `PrimerNombreUsu` VARCHAR(45) NOT NULL,
  `SegundoNombreUsu` VARCHAR(45) NULL,
  `PrimerApellidoUsu` VARCHAR(45) NOT NULL,
  `SegundoApellidoUsu` VARCHAR(45) NULL,
  `DireccionUsu` VARCHAR(45) NOT NULL,
  `TelefonoUsu` INT NULL,
  `CelularUsu` BIGINT(15) NULL,
  `EmailUsu` VARCHAR(45) NOT NULL,
  `FechaNacimientoUsu` VARCHAR(45) NOT NULL,
  `PassUsu` VARCHAR(45) NOT NULL,
  `TipoDocumento_idTipoDocumento` VARCHAR(5) NOT NULL,
  `Rol_idRol` VARCHAR(45) NOT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`PKNUsuario`, `TipoDocumento_idTipoDocumento`),
  INDEX `fk_Usuario_TipoDocumento_idx` (`TipoDocumento_idTipoDocumento` ASC),
  INDEX `fk_Usuario_Rol1_idx` (`Rol_idRol` ASC),
  INDEX `fk_Usuario_Ciudad1_idx` (`Ciudad_idCiudad` ASC),
  CONSTRAINT `fk_Usuario_TipoDocumento`
    FOREIGN KEY (`TipoDocumento_idTipoDocumento`)
    REFERENCES `pvp1`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `pvp1`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `pvp1`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvp1`.`Conteo_Visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvp1`.`Conteo_Visitas` (
  `IdConteoVisitas` INT NOT NULL AUTO_INCREMENT,
  `Visitas` INT NOT NULL,
  `Usuario_PKNUsuario` INT NOT NULL,
  `Usuario_TipoDocumento_idTipoDocumento` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`IdConteoVisitas`),
  INDEX `fk_Conteo_Visitas_Usuario1_idx` (`Usuario_PKNUsuario` ASC, `Usuario_TipoDocumento_idTipoDocumento` ASC),
  CONSTRAINT `fk_Conteo_Visitas_Usuario1`
    FOREIGN KEY (`Usuario_PKNUsuario` , `Usuario_TipoDocumento_idTipoDocumento`)
    REFERENCES `pvp1`.`Usuario` (`PKNUsuario` , `TipoDocumento_idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvp1`.`TamanoPresentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvp1`.`TamanoPresentacion` (
  `IdTamanoPresentacion` INT NOT NULL,
  `DescripcionTP` VARCHAR(45) NULL,
  PRIMARY KEY (`IdTamanoPresentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvp1`.`TipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvp1`.`TipoProducto` (
  `IdTipoProducto` INT NOT NULL,
  `DescripcionTipoProducto` VARCHAR(45) NULL,
  PRIMARY KEY (`IdTipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvp1`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvp1`.`Producto` (
  `IDProducto` INT NOT NULL,
  `DescripcionPro` VARCHAR(45) NOT NULL,
  `PrecioUnitarioPro` DECIMAL(19,5) NOT NULL,
  `ObservPro` VARCHAR(45) NOT NULL,
  `Productocol` VARCHAR(45) NOT NULL,
  `TamanoPresentacion_IdTamanoPresentacion` INT NOT NULL,
  `TipoProducto_IdTipoProducto` INT NOT NULL,
  PRIMARY KEY (`IDProducto`),
  INDEX `fk_Producto_TamanoPresentacion1_idx` (`TamanoPresentacion_IdTamanoPresentacion` ASC),
  INDEX `fk_Producto_TipoProducto1_idx` (`TipoProducto_IdTipoProducto` ASC),
  CONSTRAINT `fk_Producto_TamanoPresentacion1`
    FOREIGN KEY (`TamanoPresentacion_IdTamanoPresentacion`)
    REFERENCES `pvp1`.`TamanoPresentacion` (`IdTamanoPresentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_TipoProducto1`
    FOREIGN KEY (`TipoProducto_IdTipoProducto`)
    REFERENCES `pvp1`.`TipoProducto` (`IdTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvp1`.`Recibio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvp1`.`Recibio` (
  `idRecibio` INT NOT NULL,
  `FechaRecibo` DATE NOT NULL,
  `TotalRecibo` DECIMAL(19,5) NOT NULL,
  `Usuario_PKNUsuario` INT NOT NULL,
  `Usuario_TipoDocumento_idTipoDocumento` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idRecibio`),
  INDEX `fk_Recibio_Usuario1_idx` (`Usuario_PKNUsuario` ASC, `Usuario_TipoDocumento_idTipoDocumento` ASC),
  CONSTRAINT `fk_Recibio_Usuario1`
    FOREIGN KEY (`Usuario_PKNUsuario` , `Usuario_TipoDocumento_idTipoDocumento`)
    REFERENCES `pvp1`.`Usuario` (`PKNUsuario` , `TipoDocumento_idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvp1`.`Recibio_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvp1`.`Recibio_has_Producto` (
  `Recibio_idRecibio` INT NOT NULL,
  `Producto_IDProducto` INT NOT NULL,
  `CantidadProducto` INT NOT NULL,
  `ValorVenta` DECIMAL(19,5) NOT NULL,
  PRIMARY KEY (`Recibio_idRecibio`, `Producto_IDProducto`),
  INDEX `fk_Recibio_has_Producto_Producto1_idx` (`Producto_IDProducto` ASC),
  INDEX `fk_Recibio_has_Producto_Recibio1_idx` (`Recibio_idRecibio` ASC),
  CONSTRAINT `fk_Recibio_has_Producto_Recibio1`
    FOREIGN KEY (`Recibio_idRecibio`)
    REFERENCES `pvp1`.`Recibio` (`idRecibio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recibio_has_Producto_Producto1`
    FOREIGN KEY (`Producto_IDProducto`)
    REFERENCES `pvp1`.`Producto` (`IDProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
